
# (c) 2009 by Anton Korenyushkin

files = [File(path) for path in
         ['test_app/main.js',
          'test_app/subdir/hi.txt',
          'another_app/main.js',
          'ak/MochiKit.js',
          'ak/core.js',
          'ak/mochi-kit.js',
          'blocking_app/main.js',
          'bad_app/main.js',
          'throwing_app/main.js',
          ]]

Return('files')
