
# (c) 2009-2010 by Anton Korenyushkin

files = ([File('release/' + path) for path in
          ['test-app/__main__.js',
           'test-app/subdir/hi.txt',
           'another-app/__main__.js',
           'ak/MochiKit.js',
           'ak/__init__.js',
           'blocking-app/__main__.js',
           'bad-app/__main__.js',
           'throwing-app/__main__.js',
           ]] +
         [File('spots/test-app/test-user/test-spot/' + path) for path in
          ['__main__.js',
           'answer.js'
           ]])

Return('files')
