
# (c) 2008 by Anton Korenyushkin

Import("env")

env.Command('include.js.h', 'include.js', '\
(echo "namespace\\n{\\nconst char INCLUDE_JS[] = {";\
 xxd -i < $SOURCES;\
 echo "};\\n}";\
) > $TARGET')

sources = [
    'db.cc',
    'parser.cc',
    'translator.cc',
    'type.cc',
    'js.cc',
    'js-common.cc',
    'js-file.cc',
    'js-db.cc',
    'querist.cc',
    'error.cc',
    ]

objects = [env.Object(source)
           for source in sources]
Return('objects')
