
# (c) 2008-2010 by Anton Korenyushkin

Import("env")

env.Command('init.js.h', 'init.js', '\
(echo "namespace\\n{\\nconst char INIT_JS[] = {";\
 xxd -i < $SOURCES;\
 echo "};\\n}";\
) > $TARGET')

sources = [
    'db.cc',
    'parser.cc',
    'translator.cc',
    'common.cc',
    'js.cc',
    'js-common.cc',
    'js-file.cc',
    'js-db.cc',
    'debug.cc',
    ]

objects = [env.Object(source)
           for source in sources]
Return('objects')
